edition                      = "2018"
newline_style                = "Unix"
tab_spaces                   = 2
use_field_init_shorthand     = true
use_try_shorthand            = true
struct_field_align_threshold = 20
